<?php

/**
 * @file
 * Component module for sending Mime-encoded emails.
 */

/**
 * Implements hook_mail_alter().
 */
function mimemail_compress_mail_alter(&$message) {
  module_load_include('inc', 'mimemail_compress');
  $mailbody = $message['body'][0];
  // Separate CSS from HTML for processing.
  $parts = mimemail_compress_clean_message($mailbody);
  // Compress HTML and CSS into combined message.
  if (!empty($parts)) {
    $output = new mimemail_compress($parts['html'], $parts['css']);
    $output = $output->compress();
    $message = $output;
  }
}
